baseUri = https://think-and-get-it-production.up.railway.app/api/v1
email = user@example.com
loginEmail= admin@thinkandgetit.com
#  nahbiicj@example.com
loginPssd=Admin@123456
#  Rglqyu92!
loginEmail2 = admi@thinkandgetit.com
loginPassd2 = Admin@12345
tokenPath = data.token
#admin@thinkandgetit.com

filePath = backend-restassured-java/src/main/resources/avatar.png
tempFilePath = backend-restassured-java/src/main/resources
tempFileName = empty_avatar
format = .png



#Address
label=Home
street=KG 541 St
city=Kigali
state=Kigali City
country=Rwanda
postalCode=00000

run_time_exception = CRITICAL: Application token is empty! You must successfully login via AuthService first!.

#product
category_slug = bags-luggage
product_slug = clear-pvc-stadium-tote-bag-bags-11
product_id = 89c903cd-df0d-441a-9a68-a0b8465a3109
product2Id = 4ea4759a-cf3f-4544-806f-7c5492c9c80
unExistingId = 4ea4759a-cf3f-4544-806f-7c5492c9c80


# Product Request Test Data
product.create.name=Sports Backpack
product.create.description=Durable high-density nylon backpack perfect for hiking, travel, and sports. Features multiple compartments and water-resistant zippers.
product.create.price=45.99
product.create.comparePrice=69.99
product.create.categoryId=ddb77290-34ef-4e20-a19b-febca2c5c9d1
#product.create.tags=sports,backpack,waterproof,travel
product.create.isFeatured=false
product.create.isFlashSale=false
product.create.flashSalePrice=0.0

# Variant Test Data (Nested Array)
product.variant.size=Large
product.variant.color=Matte Black
product.variant.colorHex=#000000
product.variant.sku=BP-WTPRF-BLK-LG
product.variant.stock=120
product.variant.price=45.99