baseUri = https://think-and-get-it-production.up.railway.app/api/v1
email = user@example.com
loginEmail=dodo@gmail.com
loginPssd=Dodo1!2!3!
loginEmail2 = zunrscqn@example.com
loginPassd2 = Uccrny66!
tokenPath = data.token
#admin@thinkandgetit.com

passedEmailVerificationMessage = If an account with that email exists, a reset link has been sent.

filePath = backend-restassured-java/src/main/resources/avatar.png
tempFilePath = backend-restassured-java/src/main/resources
tempFileName = empty_avatar
format = .png