baseUri = https://think-and-get-it-production.up.railway.app/api/v1
email = user@example.com
loginEmail=dodo@gmail.com
loginPssd=Dodo1!2!3!
#admin@thinkandgetit.com
passedEmailVerificationMessage = If an account with that email exists, a reset link has been sent.

filePath = backend-restassured-java/src/main/resources/avatar.png